### ISSUE TITLE
Отсутствует файл "clean_bk_sents.txt"

### ISSUE THREAD

**Issue by RKIzmailov** [slone-nlp/bashkort-spellcheker#1]
Привет!
В эксперименте "/content/bashkort-spellcheker/experiments/06_ctc_bert.ipynb" необходимо подгружать файл "clean_bk_sents.txt"

```
with open('../data/clean_bk_sents.txt', 'r') as f:
    cs2 = [line.strip() for line in f]
print(len(cs2))
```
однако не удалось найти данный файл в репозитории
подскажи пожалуйста, где его можно найти?

**Comment by avidale** [comment]
Я этот файл в блокноте [experiments/03_seqlabelling.ipynb](https://github.com/slone-nlp/bashkort-spellcheker/blob/master/experiments/03_seqlabelling.ipynb) (раздел __Load the clean texts__ в первой части) создаю на основе текстов из https://github.com/nevmenandr/bashkir-corpus, которые я просто разбил на предложения, перемешал в рандомном порядке, и сложил в один файлик.

Выкладывать его отдельно не стал, ибо он с одной стороны большой, а с другой стороны, легко воспроизводится. Но таки если очень хочется, то [вот](https://disk.yandex.ru/d/6smZ9lwY71x2Vg) на него ссылка.

**Comment by RKIzmailov** [comment]
Спасибо большое.
Сейчас делаем spell checker для кыргызского языка и в числе прочих хотим
попробовать методики примененные для башкырского.
Спасибо за репозиторий и статью!

пн, 6 нояб. 2023 г., 17:41 David Dale ***@***.***>:
